"""Registration of admin commands, guards, text handlers and callbacks."""

from telegram import Update
from telegram.ext import CallbackQueryHandler, CommandHandler, MessageHandler, TypeHandler, filters

from .admin import (
    admin_command,
    admin_debug_command,
    blocked_user_guard,
    handle_admin_block_user_confirm,
    handle_admin_block_user_do,
    handle_admin_blocked_users,
    handle_admin_broadcast_cancel,
    handle_admin_broadcast_send,
    handle_admin_broadcast_start,
    handle_admin_broadcast_text,
    handle_admin_clear_runtime_confirm,
    handle_admin_clear_runtime_do,
    handle_admin_debug,
    handle_admin_errors_menu,
    handle_admin_export_all,
    handle_admin_export_menu,
    handle_admin_export_test,
    handle_admin_frequent_errors,
    handle_admin_frequent_errors_all,
    handle_admin_global_user_detail,
    handle_admin_user_history,
    handle_admin_user_errors,
    handle_admin_user_favorites,
    handle_admin_export_user,
    handle_admin_clear_user_runtime_confirm,
    handle_admin_clear_user_runtime_do,
    handle_admin_reset_user_confirm,
    handle_admin_reset_user_second,
    handle_admin_reset_user_do,
    handle_admin_validate_tests,
    handle_admin_manage,
    handle_admin_menu,
    handle_admin_rating,
    handle_admin_summary,
    handle_admin_test_menu,
    handle_admin_test_overview,
    handle_admin_validate_test,
    handle_admin_test_stats,
    handle_admin_test_user_detail,
    handle_admin_test_users,
    handle_admin_unblock_user,
    handle_admin_noop,
    handle_admin_test_access,
    handle_admin_test_access_users,
    handle_admin_user_access,
    handle_admin_grant_access,
    handle_admin_revoke_access,
    handle_admin_set_access,
    handle_admin_reset_access,
    handle_admin_set_access_code,
    handle_admin_test_meta,
    handle_admin_set_test_title,
    handle_admin_set_test_subject,
    handle_admin_reset_test_meta,
    handle_admin_subject,
    handle_admin_add_subject,
    handle_admin_add_test_to_subject,
    handle_admin_assign_test_subject,
    handle_admin_subject_access,
    handle_admin_set_subject_access,
    handle_admin_set_subject_code,
    handle_admin_subject_settings,
    handle_admin_rename_subject,
    handle_admin_delete_subject_confirm,
    handle_admin_delete_subject_do,
    handle_admin_move_test_subject,
    handle_admin_move_test_subject_do,
    handle_admin_detach_test_subject,
    handle_admin_user_manage,
    handle_admin_tests,
    handle_admin_users,
    handle_admin_users_recent,
    handle_admin_users_result,
    handle_admin_users_attempts,
    handle_admin_users_errors,
)

ADMIN_CALLBACKS = (
    (handle_admin_menu, r"^admin:menu$"),
    (handle_admin_summary, r"^admin:summary$"),
    (handle_admin_users_recent, r"^admin:users:recent:0$"),
    (handle_admin_users_result, r"^admin:users:result:0$"),
    (handle_admin_users_attempts, r"^admin:users:attempts:0$"),
    (handle_admin_users_errors, r"^admin:users:errors:0$"),
    (handle_admin_users, r"^admin:users:"),
    (handle_admin_global_user_detail, r"^admin:global_user:"),
    (handle_admin_block_user_confirm, r"^admin:block_user_confirm:"),
    (handle_admin_block_user_do, r"^admin:block_user_do:"),
    (handle_admin_unblock_user, r"^admin:unblock_user:"),
    (handle_admin_blocked_users, r"^admin:blocked_users:"),
    (handle_admin_broadcast_start, r"^admin:broadcast_start$"),
    (handle_admin_broadcast_send, r"^admin:broadcast_send$"),
    (handle_admin_broadcast_cancel, r"^admin:broadcast_cancel$"),
    (handle_admin_user_history, r"^admin:user_history:"),
    (handle_admin_user_errors, r"^admin:user_errors:"),
    (handle_admin_user_favorites, r"^admin:user_favorites:"),
    (handle_admin_export_user, r"^admin:export_user:"),
    (handle_admin_clear_user_runtime_confirm, r"^admin:clear_user_runtime_confirm:"),
    (handle_admin_clear_user_runtime_do, r"^admin:clear_user_runtime_do:"),
    (handle_admin_reset_user_confirm, r"^admin:reset_user_confirm:"),
    (handle_admin_reset_user_second, r"^admin:reset_user_second:"),
    (handle_admin_reset_user_do, r"^admin:reset_user_do:"),
    (handle_admin_validate_tests, r"^admin:validate_tests$"),
    (handle_admin_tests, r"^admin:tests$"),
    (handle_admin_subject_access, r"^admin:subject_access:"),
    (handle_admin_set_subject_access, r"^admin:set_subject_access:"),
    (handle_admin_set_subject_code, r"^admin:set_subject_code:"),
    (handle_admin_subject_settings, r"^admin:subject_settings:"),
    (handle_admin_rename_subject, r"^admin:rename_subject:"),
    (handle_admin_delete_subject_confirm, r"^admin:delete_subject_confirm:"),
    (handle_admin_delete_subject_do, r"^admin:delete_subject_do:"),
    (handle_admin_move_test_subject_do, r"^admin:move_test_subject_do:"),
    (handle_admin_move_test_subject, r"^admin:move_test_subject:"),
    (handle_admin_detach_test_subject, r"^admin:detach_test_subject:"),
    (handle_admin_user_manage, r"^admin:user_manage:"),
    (handle_admin_subject, r"^admin:subject:"),
    (handle_admin_add_test_to_subject, r"^admin:add_test_to_subject:"),
    (handle_admin_assign_test_subject, r"^admin:assign_test_subject:"),
    (handle_admin_add_subject, r"^admin:add_subject$"),
    (handle_admin_test_overview, r"^admin:test_overview:"),
    (handle_admin_validate_test, r"^admin:validate_test:"),
    (handle_admin_test_stats, r"^admin:test_stats:"),
    (handle_admin_rating, r"^admin:rating:"),
    (handle_admin_test_users, r"^admin:test_users:"),
    (handle_admin_test_user_detail, r"^admin:user:"),
    (handle_admin_test_user_detail, r"^admin:test_user:"),
    (handle_admin_errors_menu, r"^admin:errors$"),
    (handle_admin_frequent_errors_all, r"^admin:frequent_errors_all$"),
    (handle_admin_frequent_errors, r"^admin:frequent_errors:"),
    (handle_admin_export_menu, r"^admin:export_menu$"),
    (handle_admin_export_all, r"^admin:export_all$"),
    (handle_admin_export_test, r"^admin:export_test:"),
    (handle_admin_debug, r"^admin:debug$"),
    (handle_admin_manage, r"^admin:manage$"),
    (handle_admin_clear_runtime_confirm, r"^admin:clear_runtime_confirm$"),
    (handle_admin_clear_runtime_do, r"^admin:clear_runtime_do$"),
    (handle_admin_noop, r"^admin:noop$"),
    (handle_admin_test_access_users, r"^admin:test_access_users:"),
    (handle_admin_set_access, r"^admin:set_access:"),
    (handle_admin_reset_access, r"^admin:reset_access:"),
    (handle_admin_set_access_code, r"^admin:set_access_code:"),
    (handle_admin_test_access, r"^admin:test_access:"),
    (handle_admin_user_access, r"^admin:user_access:"),
    (handle_admin_grant_access, r"^admin:grant_access:"),
    (handle_admin_revoke_access, r"^admin:revoke_access:"),
    (handle_admin_test_meta, r"^admin:test_meta:"),
    (handle_admin_set_test_title, r"^admin:set_test_title:"),
    (handle_admin_set_test_subject, r"^admin:set_test_subject:"),
    (handle_admin_reset_test_meta, r"^admin:reset_test_meta:"),
    (handle_admin_test_menu, r"^admin:test:"),
)


def register_admin_handlers(app) -> None:
    """Register all admin-specific handlers on the application."""
    app.add_handler(CommandHandler("admin", admin_command))
    app.add_handler(CommandHandler("admin_debug", admin_debug_command))
    app.add_handler(TypeHandler(Update, blocked_user_guard), group=-2)
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_admin_broadcast_text), group=-1)

    for handler, pattern in ADMIN_CALLBACKS:
        app.add_handler(CallbackQueryHandler(handler, pattern=pattern))
