"""Registration of public/user bot commands, text input and callbacks."""

from telegram.ext import CallbackQueryHandler, CommandHandler, MessageHandler, filters

from .handlers import (
    finish_command,
    handle_answer,
    handle_attempt_error_show,
    handle_attempt_errors_page,
    handle_continue_session,
    handle_enter_access_code,
    handle_enter_subject_code,
    handle_errors_solve,
    handle_favorite_show,
    handle_find_by_number,
    handle_find_by_text,
    handle_find_question_menu,
    handle_find_results_page,
    handle_finish_button,
    handle_history_attempt,
    handle_learn_menu,
    handle_locked_subject,
    handle_locked_test,
    handle_mini_start,
    handle_my_profile,
    handle_my_stats,
    handle_next_question,
    handle_noop,
    handle_pause_to_menu,
    handle_profile_errors,
    handle_profile_error_show,
    handle_profile_favorites,
    handle_profile_history,
    handle_public_rating,
    handle_question_continue,
    handle_question_menu,
    handle_repeat_attempt,
    handle_repeat_session_errors,
    handle_reset_errors_confirm,
    handle_reset_errors_do,
    handle_result_error_show,
    handle_result_errors_page,
    handle_session_error_show,
    handle_show_answer,
    handle_show_result,
    handle_show_result_attempt,
    handle_solve_menu,
    handle_start_from_number_menu,
    handle_start_quiz,
    handle_subject_menu,
    handle_test_menu,
    handle_tests_menu,
    handle_text_input,
    handle_toggle_favorite,
    handle_view_question,
    myid,
    reset,
    reset_errors_command,
    start,
    stats_command,
    tests_command,
)

USER_CALLBACKS = (
    (handle_noop, r"^noop$"),
    (handle_tests_menu, r"^tests:menu$"),
    (handle_locked_subject, r"^locked_subject:"),
    (handle_enter_subject_code, r"^enter_subject_code:"),
    (handle_subject_menu, r"^subject_menu:"),
    (handle_locked_test, r"^locked_test:"),
    (handle_enter_access_code, r"^enter_access_code:"),
    (handle_test_menu, r"^test_menu:"),
    (handle_learn_menu, r"^learn_menu:"),
    (handle_my_profile, r"^my_profile:"),
    (handle_profile_favorites, r"^profile_favorites:"),
    (handle_favorite_show, r"^favorite_show:"),
    (handle_profile_errors, r"^profile_errors:"),
    (handle_profile_error_show, r"^profile_error_show:"),
    (handle_profile_history, r"^profile_history:"),
    (handle_history_attempt, r"^history_attempt:"),
    (handle_attempt_errors_page, r"^attempt_errors_page:"),
    (handle_attempt_error_show, r"^attempt_error_show:"),
    (handle_repeat_attempt, r"^repeat_attempt:"),
    (handle_result_errors_page, r"^result_errors_page:"),
    (handle_result_error_show, r"^result_error_show:"),
    (handle_show_result_attempt, r"^show_result_attempt:"),
    (handle_toggle_favorite, r"^toggle_favorite:"),
    (handle_solve_menu, r"^solve_menu:"),
    (handle_start_quiz, r"^start:"),
    (handle_start_from_number_menu, r"^start_from_number:"),
    (handle_mini_start, r"^mini_start:"),
    (handle_errors_solve, r"^errors_solve:"),
    (handle_find_question_menu, r"^find_question:"),
    (handle_find_by_number, r"^find_number:"),
    (handle_find_by_text, r"^find_text:"),
    (handle_view_question, r"^view_question:"),
    (handle_find_results_page, r"^find_results_page:"),
    (handle_answer, r"^answer:"),
    (handle_show_answer, r"^show_answer:"),
    (handle_next_question, r"^next_question:"),
    (handle_question_menu, r"^question_menu:"),
    (handle_question_continue, r"^question_continue:"),
    (handle_pause_to_menu, r"^pause_to_menu:"),
    (handle_continue_session, r"^continue_session:"),
    (handle_finish_button, r"^finish$"),
    (handle_session_error_show, r"^session_error_show:"),
    (handle_session_error_show, r"^session_errors:"),
    (handle_show_result, r"^show_result:"),
    (handle_repeat_session_errors, r"^repeat_session_errors:"),
    (handle_my_stats, r"^my_stats:"),
    (handle_public_rating, r"^public_rating:"),
    (handle_reset_errors_confirm, r"^reset_errors_confirm:"),
    (handle_reset_errors_do, r"^reset_errors_do:"),
)


def register_user_handlers(app) -> None:
    """Register user-facing commands, text handler and callback handlers."""
    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("tests", tests_command))
    app.add_handler(CommandHandler("finish", finish_command))
    app.add_handler(CommandHandler("stats", stats_command))
    app.add_handler(CommandHandler("reset", reset))
    app.add_handler(CommandHandler("reset_errors", reset_errors_command))
    app.add_handler(CommandHandler("myid", myid))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_text_input))

    for handler, pattern in USER_CALLBACKS:
        app.add_handler(CallbackQueryHandler(handler, pattern=pattern))
